version: 0.2
phases:
  install:
     runtime-versions:
        dotnet: 3.1
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore dotNetMvcTemplate/dotNetMvcTemplate.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output dotNetMvcTemplate/dotNetMvcTemplate.csproj
artifacts:
  files:
    - dotNetMvcTemplate/build_output/**/*
    - scripts/**/*
    - appspec.yml